# symbols.py
# 🔹 List of all stock symbols for trading scripts
symbols = [
    "NIFTY","BANKNIFTY","FINNIFTY", "MIDCPNIFTY",
    "360ONE", "ABCAPITAL", "ADANIGREEN", "ADANIPORTS", 
    "AMBUJACEM", "ASHOKLEY", "ASTRAL", "AUBANK", "AUROPHARMA", 
    "AXISBANK", "BAJFINANCE", "BANDHANBNK", "BANKBARODA", "BANKINDIA", 
    "BDL", "BEL", "BHEL", "BIOCON", "BPCL", "CAMS", "CANBK", "CDSL", 
    "CGPOWER", "CIPLA", "COALINDIA", "COFORGE", "CONCOR", "CROMPTON", 
    "DABUR", "DELHIVERY", "DLF", "DRREDDY", "ETERNAL", "EXIDEIND", 
    "FEDERALBNK", "FORTIS", "GAIL", "GMRAIRPORT", "GODREJCP", "HAVELLS", 
    "HCLTECH", "HDFCBANK", "HDFCLIFE", "HINDALCO", "HINDPETRO", "HINDZINC", 
    "HUDCO", "ICICIBANK", "ICICIPRULI", "IDEA", "IDFCFIRSTB", "IEX", 
    "INDHOTEL", "INDIANB", "INDUSINDBK", "INDUSTOWER", "INFY", "INOXWIND", 
    "IOC", "IRCTC", "IREDA", "IRFC", "ITC", "JINDALSTEL", "JIOFIN", 
    "JSWENERGY", "JSWSTEEL", "JUBLFOOD", "KALYANKJIL", "KFINTECH", 
    "KOTAKBANK", "KPITTECH", "LAURUSLABS", "LICHSGFIN", "LICI", "LODHA", 
    "LTF", "MANAPPURAM", "MARICO", "MAXHEALTH", "NATIONALUM", 
    "NAUKRI", "NBCC", "NESTLEIND", "NHPC", "NMDC", "NTPC", "NUVAMA", 
    "NYKAA", "OBEROIRLTY", "OIL", "ONGC", "PATANJALI", "PAYTM", "PETRONET", 
    "PFC", "PGEL", "PIDILITIND", "PNB", "PNBHOUSING", "POLICYBZR", "POWERGRID", 
    "PPLPHARMA","PRESTIGE", "RBLBANK", "RECLTD", "RELIANCE", 
    "RVNL", "SAIL", "SBICARD", "SBIN", "SHRIRAMFIN", "SONACOMS", 
    "SUZLON", "SWIGGY", "SYNGENE", "TATACONSUM", "TATAPOWER", "TATASTEEL", 
    "TATATECH", "TMPV", "TORNTPOWER", "UNIONBANK", "UNITDSPR", "UNOMINDA", 
    "UPL", "VBL", "VEDL", "VOLTAS", "WIPRO", "YESBANK", "ZYDUSLIFE"
    ]