# Generated by Django 6.0.1 on 2026-02-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportresistance',
            name='dist_ce_1',
            field=models.FloatField(default=0.0, verbose_name='Dist CE1 %'),
        ),
        migrations.AddField(
            model_name='supportresistance',
            name='dist_ce_2',
            field=models.FloatField(default=0.0, verbose_name='Dist CE2 %'),
        ),
        migrations.AddField(
            model_name='supportresistance',
            name='dist_pe_1',
            field=models.FloatField(default=0.0, verbose_name='Dist PE1 %'),
        ),
        migrations.AddField(
            model_name='supportresistance',
            name='dist_pe_2',
            field=models.FloatField(default=0.0, verbose_name='Dist PE2 %'),
        ),
    ]
