# Generated by Django 6.0.1 on 2026-02-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=50, unique=True)),
                ('instrument_key', models.CharField(max_length=100)),
                ('lot_size', models.IntegerField(default=1)),
                ('expiry_dates', models.JSONField(blank=True, default=list)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
