# Generated by Django 6.0.1 on 2026-02-04 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystock', '0002_supportresistance_dist_ce_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiryCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=50, unique=True)),
                ('expiries', models.JSONField(default=list)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
