# Generated by Django 6.0.1 on 2026-02-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystock', '0002_instrumentstore'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveSRData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.DateTimeField()),
                ('Symbol', models.CharField(max_length=50)),
                ('Expiry_Date', models.CharField(blank=True, max_length=20, null=True)),
                ('Spot_Price', models.FloatField(default=0.0)),
                ('ce_high_oi_strike', models.FloatField(blank=True, null=True)),
                ('ce_oi_status', models.CharField(blank=True, max_length=20, null=True)),
                ('ce_2nd_high_oi_strike', models.FloatField(blank=True, null=True)),
                ('ce_high_vol_strike', models.FloatField(blank=True, null=True)),
                ('ce_vol_status', models.CharField(blank=True, max_length=20, null=True)),
                ('ce_2nd_high_vol_strike', models.FloatField(blank=True, null=True)),
                ('pe_high_oi_strike', models.FloatField(blank=True, null=True)),
                ('pe_oi_status', models.CharField(blank=True, max_length=20, null=True)),
                ('pe_2nd_high_oi_strike', models.FloatField(blank=True, null=True)),
                ('pe_high_vol_strike', models.FloatField(blank=True, null=True)),
                ('pe_vol_status', models.CharField(blank=True, max_length=20, null=True)),
                ('pe_2nd_high_vol_strike', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
