# Generated by Django 6.0.1 on 2026-02-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystock', '0003_expirycache'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempOptionChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.DateTimeField(db_index=True)),
                ('Expiry_Date', models.DateField(blank=True, db_index=True, null=True)),
                ('Symbol', models.CharField(db_index=True, max_length=50)),
                ('Strike_Price', models.FloatField(db_index=True)),
                ('CE_Delta', models.FloatField(blank=True, null=True)),
                ('CE_RANGE', models.FloatField(blank=True, null=True)),
                ('CE_IV', models.FloatField(blank=True, null=True)),
                ('CE_COI_percent', models.FloatField(blank=True, null=True)),
                ('CE_COI', models.FloatField(blank=True, null=True)),
                ('CE_OI_percent', models.FloatField(blank=True, null=True)),
                ('CE_OI', models.FloatField(blank=True, null=True)),
                ('CE_Volume_percent', models.FloatField(blank=True, null=True)),
                ('CE_Volume', models.FloatField(blank=True, null=True)),
                ('CE_CLTP', models.FloatField(blank=True, null=True)),
                ('CE_LTP', models.FloatField(blank=True, null=True)),
                ('Reversl_Ce', models.FloatField(blank=True, null=True)),
                ('Reversl_Pe', models.FloatField(blank=True, null=True)),
                ('PE_LTP', models.FloatField(blank=True, null=True)),
                ('PE_CLTP', models.FloatField(blank=True, null=True)),
                ('PE_Volume', models.FloatField(blank=True, null=True)),
                ('PE_Volume_percent', models.FloatField(blank=True, null=True)),
                ('PE_OI', models.FloatField(blank=True, null=True)),
                ('PE_OI_percent', models.FloatField(blank=True, null=True)),
                ('PE_COI', models.FloatField(blank=True, null=True)),
                ('PE_COI_percent', models.FloatField(blank=True, null=True)),
                ('PE_IV', models.FloatField(blank=True, null=True)),
                ('PE_RANGE', models.FloatField(blank=True, null=True)),
                ('PE_Delta', models.FloatField(blank=True, null=True)),
                ('Spot_Price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['Strike_Price'],
            },
        ),
    ]
