# Generated by Django 6.0.1 on 2026-02-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystock', '0003_livesrdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesrdata',
            name='resistance_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='livesrdata',
            name='resistance_strike',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livesrdata',
            name='supprt_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='livesrdata',
            name='supprt_strike',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
