# Generated by Django 6.0.1 on 2026-03-11 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystock', '0004_livesrdata_resistance_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livesrdata',
            name='resistance_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='livesrdata',
            name='supprt_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
