# Generated by Django 6.0.1 on 2026-02-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystock', '0004_tempoptionchain'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempoptionchain',
            name='Lot_size',
            field=models.IntegerField(default=1),
        ),
    ]
