# Generated by Django 6.0.1 on 2026-02-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystock', '0005_tempoptionchain_lot_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionchain',
            name='Lot_size',
            field=models.IntegerField(default=1),
        ),
    ]
