# Generated by Django 6.0.1 on 2026-02-06 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystock', '0006_optionchain_lot_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportresistance',
            name='Symbol',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='supportresistance',
            name='Time',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
