# Generated by Django 6.0.1 on 2026-02-06 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystock', '0007_alter_supportresistance_symbol_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportresistance',
            options={},
        ),
        migrations.AddIndex(
            model_name='supportresistance',
            index=models.Index(fields=['Symbol', '-Time'], name='Support_Res_Symbol_a05ee6_idx'),
        ),
    ]
