# Generated by Django 6.0.1 on 2026-02-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystock', '0008_alter_supportresistance_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportresistance',
            name='Expiry_Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
