# Generated by Django 6.0.6 on 2026-07-16 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystock', '0016_voicecommand'),
    ]

    operations = [
        migrations.CreateModel(
            name='LtpLevels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('symbol', models.CharField(db_index=True, max_length=50)),
                ('expiry_date', models.CharField(blank=True, max_length=20, null=True)),
                ('market_price', models.FloatField(verbose_name='Market Price (Spot)')),
                ('ce_strike', models.FloatField(verbose_name='CE Strike (ऊपर वाली)')),
                ('ce_ltp', models.FloatField(verbose_name='CE LTP')),
                ('pe_strike', models.FloatField(verbose_name='PE Strike (नीचे वाली)')),
                ('pe_ltp', models.FloatField(verbose_name='PE LTP')),
                ('ltp_total', models.FloatField(verbose_name='LTP Total (CE+PE)')),
                ('r1', models.FloatField(verbose_name='R1')),
                ('r2', models.FloatField(verbose_name='R2')),
                ('r3', models.FloatField(verbose_name='R3')),
                ('s1', models.FloatField(verbose_name='S1')),
                ('s2', models.FloatField(verbose_name='S2')),
                ('s3', models.FloatField(verbose_name='S3')),
            ],
            options={
                'verbose_name': 'LTP Levels',
                'verbose_name_plural': 'LTP Levels',
                'ordering': ['-saved_at'],
            },
        ),
    ]
