# Generated by Django 6.0.6 on 2026-07-27 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mystock', '0017_ltp_levels_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VoiceCommand',
        ),
    ]
