# Generated by Django 6.0.6 on 2026-07-28 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystock', '0018_remove_voicecommand'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticReversal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Symbol')),
                ('saved_at', models.DateTimeField(auto_now=True, verbose_name='Last Saved At')),
                ('spot_price', models.FloatField(verbose_name='Spot Price at Save Time')),
                ('levels_json', models.JSONField(default=list, verbose_name='Reversal Levels (JSON)')),
            ],
            options={
                'verbose_name': 'Static Reversal',
                'ordering': ['symbol'],
            },
        ),
    ]
