# Generated by Django 6.0.6 on 2026-07-31 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystock', '0019_staticreversal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staticreversal',
            options={'ordering': ['symbol', 'reversal_type'], 'verbose_name': 'Static Reversal'},
        ),
        migrations.AddField(
            model_name='staticreversal',
            name='filter_value',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Filter Value (expiry/date string)'),
        ),
        migrations.AddField(
            model_name='staticreversal',
            name='reversal_type',
            field=models.CharField(choices=[('LSR', 'Live Static Reversal'), ('ESR', 'Expiry Static Reversal'), ('DSR', 'Date Static Reversal')], default='LSR', max_length=3, verbose_name='Type (LSR/ESR/DSR)'),
        ),
        migrations.AlterField(
            model_name='staticreversal',
            name='symbol',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Symbol'),
        ),
        migrations.AlterUniqueTogether(
            name='staticreversal',
            unique_together={('symbol', 'reversal_type', 'filter_value')},
        ),
    ]
