# symbols.py
# 🔹 List of all stock symbols for trading scripts
symbols = [
"NIFTY","BANKNIFTY","FINNIFTY", "MIDCPNIFTY",
    "360ONE", "ABB", "ABCAPITAL", "ADANIENT", "ADANIGREEN", "ADANIPORTS", 
    "ALKEM", "AMBER", "AMBUJACEM", "ANGELONE", "APLAPOLLO", "APOLLOHOSP", 
    "ASHOKLEY", "ASIANPAINT", "ASTRAL", "AUBANK", "AUROPHARMA", "AXISBANK", 
    "BAJAJ-AUTO", "BAJAJFINSV", "BAJAJHLDNG", "BAJFINANCE", "BANDHANBNK", 
    "BANKBARODA", "BANKINDIA", "BDL", "BEL", "BHARATFORG", "BHARTIARTL", 
    "BHEL", "BIOCON", "BLUESTARCO", "BOSCHLTD", "BPCL", "BRITANNIA", "BSE", 
    "CAMS", "CANBK", "CDSL", "CGPOWER", "CHOLAFIN", "CIPLA", "COALINDIA", 
    "COFORGE", "COLPAL", "CONCOR", "CROMPTON", "CUMMINSIND", "DABUR", 
    "DALBHARAT", "DELHIVERY", "DIVISLAB", "DIXON", "DLF", "DMART", "DRREDDY", 
    "EICHERMOT", "ETERNAL", "EXIDEIND", "FEDERALBNK", "FORTIS", "GAIL", 
    "GLENMARK", "GMRAIRPORT", "GODREJCP", "GODREJPROP", "GRASIM", "HAL", 
    "HAVELLS", "HCLTECH", "HDFCAMC", "HDFCBANK", "HDFCLIFE", "HEROMOTOCO", 
    "HINDALCO", "HINDPETRO", "HINDUNILVR", "HINDZINC", "HUDCO", "ICICIBANK", 
    "ICICIGI", "ICICIPRULI", "IDEA", "IDFCFIRSTB", "IEX", "INDHOTEL", 
    "INDIANB", "INDIGO", "INDUSINDBK", "INDUSTOWER", "INFY", "INOXWIND", 
    "IOC", "IRCTC", "IREDA", "IRFC", "ITC", "JINDALSTEL", "JIOFIN", 
    "JSWENERGY", "JSWSTEEL", "JUBLFOOD", "KALYANKJIL", "KAYNES", "KEI", 
    "KFINTECH", "KOTAKBANK", "KPITTECH", "LAURUSLABS", "LICHSGFIN", "LICI", 
    "LODHA", "LT", "LTF", "LTIM", "LUPIN", "M&M", "MANAPPURAM", "MANKIND", 
    "MARICO", "MARUTI", "MAXHEALTH", "MAZDOCK", "MCX", "MFSL", "MOTHERSON", 
    "MPHASIS", "MUTHOOTFIN", "NATIONALUM", "NAUKRI", "NBCC", "NESTLEIND", 
    "NHPC", "NMDC", "NTPC", "NUVAMA", "NYKAA", "OBEROIRLTY", "OFSS", "OIL", 
    "ONGC", "PAGEIND", "PATANJALI", "PAYTM", "PERSISTENT", "PETRONET", "PFC", 
    "PGEL", "PHOENIXLTD", "PIDILITIND", "PIIND", "PNB", "PNBHOUSING", 
    "POLICYBZR", "POLYCAB", "POWERGRID", "POWERINDIA", "PPLPHARMA", 
    "PREMIERENE", "PRESTIGE", "RBLBANK", "RECLTD", "RELIANCE", "RVNL", 
    "SAIL", "SAMMAAN", "SBICARD", "SBILIFE", "SBIN", "SHREECEM", 
    "SHRIRAMFIN", "SIEMENS", "SOLARINDS", "SONACOMS", "SRF", "SUNPHARMA", 
    "SUPREMEIND", "SUZLON", "SWIGGY", "SYNGENE", "TATACONSUM", "TATAELXSI", 
    "TATAPOWER", "TATASTEEL", "TATATECH", "TCS", "TECHM", "TIINDIA", "TITAN", 
    "TMPV", "TORNTPHARM", "TORNTPOWER", "TRENT", "TVSMOTOR", "ULTRACEMCO", 
    "UNIONBANK", "UNITDSPR", "UNOMINDA", "UPL", "VBL", "VEDL", "VOLTAS", 
    "WAAREEENER", "WIPRO", "YESBANK", "ZYDUSLIFE"
]
# symbols = [
#     "NIFTY",
#     "BANKNIFTY",
#     "FINNIFTY", 
#     "MIDCPNIFTY",
#     "360ONE",
#     "ABCAPITAL",
#     "ADANIENSOL",
#     "ADANIGREEN",
#     "ADANIPORTS",
#     "AMBUJACEM",
#     "ASHOKLEY",
#     "ASTRAL",
#     "AUBANK",
#     "AUROPHARMA",
#     "AXISBANK",
#     "BAJFINANCE",
#     "BANDHANBNK",
#     "BANKBARODA",
#     "BANKINDIA",
#     "BDL",
#     "BEL",
#     "BHARATFORG",
#     "BHEL",
#     "BIOCON",
#     "BPCL",
#     "CANBK",
#     "CGPOWER",
#     "COALINDIA",
#     "CONCOR",
#     "CROMPTON",
    
#     "DABUR",
#     "DELHIVERY",
#     "DLF",
#     "DRREDDY",
#     "ETERNAL",
#     "EXIDEIND",
#     "FEDERALBNK",
#     "FORTIS",
#     "GAIL",
#     "GMRAIRPORT",
#     "GODREJCP",
#     "HCLTECH",
#     "HDFCBANK",
#     "HDFCLIFE",
    
#     "HINDALCO",
#     "HINDPETRO",
#     "HINDZINC",
#     "HUDCO",
#     "ICICIBANK",
#     "ICICIPRULI",
#     "IDEA",
#     "IDFCFIRSTB",
#     "IEX",
    
#     "IIFL",
#     "INDHOTEL",
#     "INDIANB",
#     "INDUSINDBK",
#     "INDUSTOWER",
#     "INFY",
#     "INOXWIND",
#     "IOC",
#     "IRCTC",
#     "IREDA",
#     "IRFC",
#     "ITC",
#     "JINDALSTEL",
#     "JIOFIN",
#     "JSWENERGY",
#     "JSWSTEEL",
#     "JUBLFOOD",
#     "KALYANKJIL",
#     "KFINTECH",
#     "KPITTECH",
#     "LAURUSLABS",
#     "LICHSGFIN",
#     "LICI",
#     "LODHA",
#     "LTF",
#     "MANAPPURAM",
#     "MARICO",
#     "MAXHEALTH",
    
#     "NATIONALUM",
#     "NAUKRI",
#     "NBCC",
    
#     "NESTLEIND",
#     "NHPC",
#     "NMDC",
#     "NTPC",
#     "NYKAA",
#     "OIL",
#     "ONGC",
#     "PAYTM",
#     "PETRONET",
#     "PFC",
#     "PGEL",
#     "PNB",
#     "PNBHOUSING",
#     "POWERGRID",
#     "PPLPHARMA",
#     "RBLBANK",
#     "RECLTD",
#     "RELIANCE",
#     "RVNL",
#     "SAIL",
#     "SAMMAANCAP",
#     "SBICARD",
#     "SBIN",
#     "SHRIRAMFIN",
#     "SONACOMS",
#     "SUZLON",
#     "SYNGENE",
#     "TATACONSUM",
#     "TATAMOTORS",
#     "TATAPOWER",
#     "TATASTEEL",
#     "TATATECH",
#     "TECHM",
#     "TITAGARH",
#     "TORNTPOWER",
#     "UNIONBANK",
#     "UNITDSPR",
#     "UNOMINDA",
    
#     "UPL",
#     "VBL",
#     "VEDL",
#     "VOLTAS",
#     "WIPRO",
#     "YESBANK",
#     "ZYDUSLIFE"
# ]
