# symbols.py
# 🔹 List of all stock symbols for trading scripts
symbols = [
    "NIFTY",
    "BANKNIFTY","FINNIFTY", "MIDCPNIFTY",
    'ABCAPITAL', 'ADANIPOWER', 'AMBUJACEM', 'ANGELONE', 'ASHOKLEY', 'BANDHANBNK', 
    'BANKBARODA', 'BANKINDIA', 'BEL', 'BHEL', 'BIOCON', 'BPCL', 'CAMS', 'CANBK', 
    'CGPOWER', 'COALINDIA', 'CONCOR', 'CROMPTON', 'DABUR', 'DELHIVERY', 'DLF', 
    'ETERNAL', 'EXIDEIND', 'FEDERALBNK', 'FORTIS', 'GAIL', 'GMRAIRPORT', 'HDFCBANK', 
    'HDFCLIFE', 'HINDALCO', 'HINDPETRO', 'HINDZINC', 'ICICIPRULI', 'IDEA', 'IDFCFIRSTB', 
    'IEX', 'INDHOTEL', 'INDIANB', 'INDUSTOWER', 'INOXWIND', 'IOC', 'IREDA', 'IRFC', 
    'ITC', 'JIOFIN', 'JSWENERGY', 'JUBLFOOD', 'KALYANKJIL', 'KFINTECH', 'KOTAKBANK', 
    'KPITTECH', 'LICHSGFIN', 'LICI', 'LTF', 'MANAPPURAM', 'MARICO', 'MOTHERSON', 
    'MOTILALOFS', 'NATIONALUM', 'NBCC', 'NHPC', 'NMDC', 'NTPC', 'NYKAA', 'OIL', 'ONGC', 
    'PATANJALI', 'PETRONET', 'PFC', 'PGEL', 'PNB', 'POWERGRID', 'RBLBANK', 'RECLTD', 
    'RVNL', 'SAIL', 'SBICARD', 'SONACOMS', 'SUZLON', 'SWIGGY', 'TATAPOWER', 'TATASTEEL', 
    'TMPV', 'UNIONBANK', 'UPL', 'VBL', 'VEDL', 'VMM', 'WIPRO', 'YESBANK'
]
